# name: Deploy to S3 + CloudFront

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       # 1️⃣ Clone source code từ GitHub
#       - name: Checkout source
#         uses: actions/checkout@v4

#       # 2️⃣ Cài Node và build Next.js
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20 # Next 16 hỗ trợ Node 18+, nên dùng 20 cho ổn định

#       # Nếu website là Next.js static export thì thêm:
#       - name: Build static files
#         run: |
#           yarn install
#           yarn build

#       - name: Sync files to S3 (private bucket)
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --delete
#         env:
#           AWS_S3_BUCKET: siucode-lab-bucket
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: ap-southeast-1
#           SOURCE_DIR: ./out

#       - name: Invalidate CloudFront cache
#         uses: chetan/invalidate-cloudfront-action@v2
#         env:
#           DISTRIBUTION: ED816HOW2G2J7 # ID (xem trong CloudFront)
#           PATHS: "/*"
#           AWS_REGION: ap-southeast-1
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

name: Deploy Next.js to S3 + CloudFront

on:
  push:
    branches: [main]

permissions:
  id-token: write # Quan trọng: cho phép GitHub cấp OIDC token
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build & Export
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::482364569290:role/GitHubActionsDeployRole
          aws-region: ap-southeast-1

      - name: Sync files to S3 (private bucket)
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: siucode-lab-bucket
          AWS_REGION: ap-southeast-1
          SOURCE_DIR: ./out

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ED816HOW2G2J7
          PATHS: "/*"
          AWS_REGION: ap-southeast-1
